#Movie Database

#Query1:

SELECT MOV_TITLE
FROM MOVIES
WHERE DIR_ID = ( SELECT DIR_ID
FROM DIRECTOR
WHERE DIR_NAME='Hitchcock');

#Query2:

SELECT MOV_TITLE
FROM MOVIES
NATURAL JOIN MOVIE_CAST
WHERE ACT_ID IN ( SELECT ACT_ID
FROM MOVIE_CAST
GROUP BY ACT_ID
HAVING COUNT(*)>1 )
GROUP BY MOV_TITLE
HAVING COUNT(*)>0;

#Query3:

SELECT ACT_ID, ACT_NAME
FROM ACTOR
NATURAL JOIN MOVIE_CAST
NATURAL JOIN MOVIES
GROUP BY ACT_ID, ACT_NAME
HAVING
COUNT( CASE WHEN MOV_YEAR < 2000 THEN 1 END ) > 0
AND COUNT( CASE WHEN MOV_YEAR > 2015 THEN 1 END) > 0;

#Query4:

SELECT MOV_TITLE, MAX(REV_STARS)
FROM MOVIES
NATURAL JOIN RATING
GROUP BY MOV_TITLE
HAVING MAX(REV_STARS) > 0
ORDER BY MOV_TITLE;

#Query5:

UPDATE RATING
SET REV_STARS=5
WHERE MOV_ID IN 
(SELECT MOV_ID
FROM MOVIES
NATURAL JOIN DIRECTOR
WHERE DIR_NAME='Steven Spielberg' );