#College Database p4

#Query1:

SELECT STUDENT.*, SEM, SEC
FROM STUDENT
        NATURAL JOIN SEMSEC
        NATURAL JOIN CLASS
WHERE SEM=4 AND SEC='C';

#Query2:

SELECT SEM, SEC, GNDER, COUNT(*) AS COUNT
FROM STUDENT
NATURAL JOIN SEMSEC
ATURAL JOIN CLASS
GROUP BY SEM, SEC, GENDER

#Query3:

CREATE VIEW STUDENT_TEST1_MARKS
AS
SELECT TEST1, SUBCODE
FROM IAMARKS
WHERE USN='1BI15CS101';

#Query4:

UPDATE IAMARKS
SET FINALIA = GREATEST((test1+test2)/2, (test2+test3)/2, (test3+test1)/2);

#Query5:

SELECT STUDENT.*, SUBCODE,
( CASE
          WHEN FINALIA BETWEEN 17 AND 20 THEN 'Outstanding'
          WHEN FINALIA BETWEEN 12 AND 16 THEN 'Average'
          ELSE 'Weak'
        END ) AS CAT
FROM IAMARKS
        NATURAL JOIN STUDENT
        NATURAL JOIN SEMSEC
        NATURAL JOIN SUBJECT
WHERE SEM=8
        AND SEC IN ('A', 'B', 'C');